// 🧠 Estructura y atributos de las tablas (para ayudar a Gemini a entender)
export const TABLA_ATRIBUTOS = {
  Configuracion: {
    created_at: "timestamp with time zone",
    value: "text",
    key: "text",
    id_usuario: "bigint",
    id: "bigint",
  },
  Detalle_Visitas: {
    id: "bigint",
    detalle: "text",
    created_at: "timestamp with time zone",
    id_maquina: "bigint",
    id_visita: "bigint",
  },
  Empresa: {
    direccion: "text",
    nombre: "text",
    ruc: "text",
    id: "bigint",
    created_at: "timestamp with time zone",
    estado: "boolean",
    distrito: "text",
  },
  Encargado: {
    id: "bigint",
    foto: "bytea",
    id_planta: "bigint",
    celular: "integer",
    cargo: "text",
    pass: "text",
    email: "text",
    nombre: "text",
    apellido: "text",
    dni: "text",
    created_at: "timestamp with time zone",
    nacimiento: "date",
  },
  Maquinas: {
    marca: "text",
    id: "bigint",
    created_at: "timestamp with time zone",
    id_planta: "bigint",
    foto: "bytea",
    estado: "boolean",
    id_empresa: "bigint",
    serie: "text",
    modelo: "text",
    detalles: "text",
    linea: "text",
  },
  Planta: {
    direccion: "text",
    nombre: "text",
    id: "bigint",
    created_at: "timestamp with time zone",
    estado: "boolean",
    id_empresa: "bigint",
  },
  Reporte_Servicio: {
    entrada: "time without time zone",
    id: "bigint",
    created_at: "timestamp with time zone",
    sin_garantia: "boolean",
    facturado: "boolean",
    fecha: "timestamp with time zone",
    id_encargado: "bigint",
    en_prueba: "boolean",
    no_facturado: "boolean",
    id_empresa: "bigint",
    fotos_observaciones: "ARRAY",
    foto_firma: "bytea",
    fotos_acciones_realizadas: "ARRAY",
    operativo: "boolean",
    salida: "time without time zone",
    inoperativo: "boolean",
    con_garantia: "boolean",
    id_usuario: "bigint",
    estado: "boolean",
    codigo_reporte: "text",
    observaciones: "text",
    nombre_usuario: "text",
    celular_usuario: "text",
    serie_maquina: "text",
    linea_maquina: "text",
    marca_maquina: "text",
    modelo_maquina: "text",
    url_pdf: "text",
    problemas_encontrados: "text",
    fotos_problemas_encontrados: "ARRAY",
    nombre_planta: "text",
    acciones_realizadas: "text",
  },
  Roles: {
    nombre: "text",
    created_at: "timestamp with time zone",
    id: "bigint",
  },
  Usuarios: {
    email: "text",
    rol: "bigint",
    pass: "bigint",
    id: "bigint",
    dni: "bigint",
    estado: "boolean",
    nombres: "text",
    fotoPerfil: "text",
    celular: "bigint",
    usuario: "text",
  },
  Visitas: {
    id_planta: "bigint",
    descripcion: "text",
    id_usuario: "bigint",
    fecha: "timestamp with time zone",
    id: "bigint",
    created_at: "timestamp with time zone",
  },
  empresa: {
    direccion: "text",
    ruc: "text",
    distrito: "text",
    created_at: "timestamp with time zone",
    id: "bigint",
    nombre: "text",
  },
  role_permissions: {
    role_id: "bigint",
    created_at: "timestamp with time zone",
    permission_name: "text",
  },
};
// 🔹 Tablas disponibles
export const TABLES_NAMES = Object.keys(TABLA_ATRIBUTOS);

// 🔹 Información fija de la empresa (solo ejemplo)
export const DATA_SERVICE = {
  empresa: {
    nombre: "BAECHLER INGENIEROS",
    direccion: "Av. Siempre Viva 123",
    telefono: "+56 9 1234 5678",
    email: "info@baechleringenieros.com",
  },
};
